# WARNING #
# THIS IS AN INSANELY DANGEROUS SCRIPT #
# THIS WILL QUITE LITERALLY DELETE ALL OF THESE FILES WITHIN YOUR CURRENT DIRECTORY #
# THIS CAN DESTROY YOUR COMPUTER FOREVER #
# pwd TO CHECK YOUR IN RIGHT DIRECTORY #
# THIS IS EXTREMELY DANGEROUS STOP IT #
# COMMENT IT OUT WHEN YOUR DONE SO YOU SEE THIS MESSAGE ALL THE TIME #
# rm *.aux
# rm *.log
# rm *.gz
# rm *.fls
# rm *.toc
# rm *.fdb_latexmk
# rm *.pdf