(define (add-leaf t x)
  (if (is-leaf t)
    (tree (label t) nil)
    (tree (label t)
      (append (map (lambda (b) (add-leaf b x)) (branches t))
              (list (tree x nil))
      )
    )
  )
)
